<?php

/**
 * @file
 * Code for the MyAbility AI Text To Speech module install/update functions.
 */

/**
 * Implements hook_schema().
 */
function myability_ai_tts_schema(): array {
  $schema['myability_ai_tts_config'] = [
    'description' => 'Stores Text To Speech configurations.',
    'fields' => [
      'id' => [
        'description' => 'Primary Key: Unique configuration ID.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'source_field' => [
        'description' => 'The source field for the Text To Speech.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'target_field' => [
        'description' => 'The target field for the Text To Speech.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'voice' => [
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
      ],
      'response_format' => [
        'type' => 'varchar',
        'length' => 16,
        'not null' => TRUE,
      ],
      'speed' => [
        'type' => 'float',
        'not null' => TRUE,
      ],
      'status' => [
        'description' => 'The status of the configuration (active/inactive).',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 1,
      ],
      'entity_type' => [
        'description' => 'The entity type for which the configuration is defined.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'instructions' => [
        'description' => 'Additional instructions for the Text To Speech.',
        'type' => 'text',
        'not null' => FALSE,
      ],
    ],
    'primary key' => ['id'],
  ];

  $schema['myability_ai_tts_config_bundle'] = [
    'description' => 'Stores the bundles associated with each Text To Speech configuration.',
    'fields' => [
      'config_id' => [
        'description' => 'The ID of the Text To Speech configuration.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'bundle' => [
        'description' => 'The bundle associated with the configuration.',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
    ],
    'primary key' => ['config_id', 'bundle'],
    'indexes' => [
      'config_id' => ['config_id'],
    ],
  ];

  return $schema;
}

/**
 * Add instructions field to the 'myability_ai_tts_config' table.
 */
function myability_ai_tts_update_7001(): void {
  db_add_field('myability_ai_tts_config', 'instructions', [
    'description' => 'Additional instructions for the Text To Speech.',
    'type' => 'text',
    'not null' => FALSE,
  ]);
}
